export const FaceApiService = [
    {
        id: 1,
        title: "Children's haircut",
        suptitle: "This haircut is intended for young children (usually under 12 years old). Includes a quick and comfortable haircut process, taking into account the fact that children can be restless. Barbers use techniques to help calm children and make the experience enjoyable.",
        price: 6,
        service: "Main services",
    },
    {
        id: 2,
        title: "Schoolboy haircut",
        suptitle: "A haircut for schoolchildren (usually between the ages of 7 and 14), aimed at creating a neat and stylish look that meets school requirements. Includes modern and classic styles suitable for school events and everyday life.",
        price: 8,
        service: "Main services",
    },
    {
        id: 3,
        title: "Student haircut",
        suptitle: "Haircut for students (usually over 15 years old) who want to look fashionable and stylish. Current trends and preferences of young people are taken into account. Barbers can offer a variety of styling options to suit university life and active lifestyles.",
        price: 12,
        service: "Main services",
    },
    {
        id: 4,
        title: "Man's haircut",
        suptitle: "Classic and modern haircut for men of all ages. Includes various techniques such as fade, undercut, pompadour and other popular styles. The barber can also offer advice on hair care and styling.",
        price: 15,
        service: "Main services",
    },
    {
        id: 5,
        title: "Pensioner haircut",
        suptitle: "A special haircut for older people that takes into account their special needs. Typically involves a softer, gentler approach, taking into account the client's hair type and wishes. Barbers can offer classic and comfortable styles that are easy to maintain at home.",
        price: 12,
        service: "Main services",
    },
    {
        id: 6,
        title: "Classic Shave",
        suptitle: "Shaving with a straight razor or safety razor using special shaving products like foam, gel, or cream. It usually includes pre-steaming the skin and post-shave care to prevent irritation.",
        price: 10,
        service: "Shaving services",
    },
    {
        id: 7,
        title: "Wet Shave",
        suptitle: "This shaving method involves using water, soap, or shaving cream, which allows for a smoother shave and reduces the risk of cuts and irritation.",
        price: 8,
        service: "Shaving services",
    },
    {
        id: 8,
        title: "Beard and Mustache Care",
        suptitle: "Shaping, trimming, and caring for the beard and mustache, including washing, combing, and applying special oils and balms for moisturizing and styling.",
        price: 12,
        service: "Shaving services",
    },
    {
        id: 9,
        title: "Beard Trimming and Shaping",
        suptitle: "Trimming and creating precise lines, using a trimmer and scissors to give the beard the desired shape.",
        price: 10,
        service: "Shaving services",
    },
    {
        id: 10,
        title: "Post-Shave Skincare",
        suptitle: "Applying lotions, balms, and creams after shaving to moisturize and soothe the skin, preventing irritation and ingrown hairs.",
        price: 5,
        service: "Shaving services",
    },
    {
        id: 11,
        title: "Royal Shave",
        suptitle: "A luxurious ritual that includes several stages of care, usually involving hot towels, high-quality shaving products, and thorough post-shave skincare.",
        price: 20,
        service: "Shaving services",
    },
    {
        id: 12,
        title: "Hair and Beard Coloring",
        suptitle: "Services for coloring hair and beard, including classic coloring, highlights, toning, and creative coloring.",
        price: 15,
        service: "Additional services",
    },
    {
        id: 13,
        title: "Eyebrow Correction",
        suptitle: "Shaping and correcting the shape of the eyebrows using wax, tweezers, or threading.",
        price: 8,
        service: "Additional services",
    },
    {
        id: 14,
        title: "Head Massage",
        suptitle: "A relaxing head massage that helps relieve tension and improve blood circulation.",
        price: 10,
        service: "Additional services",
    },
    {
        id: 15,
        title: "Face Massage",
        suptitle: "A service that includes various massage techniques to improve skin tone and relieve stress.",
        price: 12,
        service: "Additional services",
    },
    {
        id: 16,
        title: "Facial Skin Care",
        suptitle: "Cleansing masks, scrubs, moisturizing, and treatments to improve the condition of the facial skin.",
        price: 15,
        service: "Additional services",
    },
    {
        id: 17,
        title: "Ear and Nose Care",
        suptitle: "Removal of excess hair in the ears and nose using wax or a trimmer.",
        price: 5,
        service: "Additional services",
    },
    {
        id: 18,
        title: "Paraffin Therapy for Hands",
        suptitle: "A service that involves applying warm paraffin to the hands for moisturizing and softening the skin.",
        price: 10,
        service: "Additional services",
    }
];
